CREATE EXTENSION IF NOT EXISTS pg_trgm;

ALTER TABLE reservation ADD COLUMN IF NOT EXISTS "purposeType" varchar(16);
ALTER TABLE reservation ADD COLUMN IF NOT EXISTS "needsMultimedia" boolean NOT NULL DEFAULT false;
ALTER TABLE reservation ADD COLUMN IF NOT EXISTS "cancelledAt" timestamp without time zone;

CREATE TABLE IF NOT EXISTS reservationcanceltoken (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "reservationId" integer NOT NULL REFERENCES reservation(id) ON DELETE CASCADE,
    "tokenHash" varchar(128) NOT NULL UNIQUE,
    "expiresAt" timestamp without time zone NOT NULL,
    "usedAt" timestamp without time zone,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS outboxjob (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind varchar(64) NOT NULL,
    payload jsonb NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'pending',
    attempts integer NOT NULL DEFAULT 0,
    "availableAt" timestamp without time zone NOT NULL DEFAULT now(),
    "lockedAt" timestamp without time zone,
    "lastError" text,
    "createdAt" timestamp without time zone NOT NULL DEFAULT now(),
    "completedAt" timestamp without time zone
);

CREATE INDEX IF NOT EXISTS reservation_room_status_time_idx
  ON reservation ("roomId", status, "startTime", "endTime");
CREATE INDEX IF NOT EXISTS reservation_email_created_idx
  ON reservation (email, "createdAt");
CREATE INDEX IF NOT EXISTS reservation_status_id_idx
  ON reservation (status, id DESC);
CREATE INDEX IF NOT EXISTS reservation_room_name_trgm_idx
  ON room USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS reservation_student_name_trgm_idx
  ON reservation USING gin ("studentName" gin_trgm_ops);
CREATE INDEX IF NOT EXISTS reservation_email_trgm_idx
  ON reservation USING gin (email gin_trgm_ops);
CREATE INDEX IF NOT EXISTS reservation_reason_trgm_idx
  ON reservation USING gin (reason gin_trgm_ops);
CREATE INDEX IF NOT EXISTS reservation_cancel_token_hash_idx
  ON reservationcanceltoken ("tokenHash");
CREATE INDEX IF NOT EXISTS outboxjob_claim_idx
  ON outboxjob (status, "availableAt");

-- The historical database contains duplicate roomapprover pairs.  Do not add
-- a unique index during the online migration; the preflight report lists the
-- duplicate pairs for a later, explicitly approved cleanup window.
